import { Local } from './local';

export const Locals: Local[] = [
      { id: 1, district: 1, localNumber: 1},
      { id: 2, district: 1, localNumber: 2},
      { id: 3, district: 1, localNumber: 3},
      { id: 4, district: 1, localNumber: 4},
      { id: 5, district: 2, localNumber: 1},
      { id: 6, district: 2, localNumber: 2},
      { id: 7, district: 2, localNumber: 3},
      { id: 8, district: 2, localNumber: 4},
      { id: 9, district: 2, localNumber: 5},
      { id: 10, district: 3, localNumber: 1},
      { id: 11, district: 3, localNumber: 2},
      { id: 12, district: 3, localNumber: 3},
      { id: 13, district: 3, localNumber: 4},
      { id: 14, district: 3, localNumber: 5},
      { id: 15, district: 3, localNumber: 6},
      { id: 16, district: 4, localNumber: 1},
      { id: 17, district: 4, localNumber: 2},
      { id: 18, district: 4, localNumber: 3},
      { id: 19, district: 4, localNumber: 4},
      { id: 20, district: 4, localNumber: 5},
      { id: 21, district: 4, localNumber: 6},
      { id: 22, district: 5, localNumber: 1},
      { id: 23, district: 5, localNumber: 2},
      { id: 24, district: 5, localNumber: 3},
      { id: 25, district: 5, localNumber: 4},
      { id: 26, district: 5, localNumber: 5},

    ];
