import { Event } from './event';

export const Events: Event[] = [
      { id: 1, title: 'Cisza przed burza', description: 'Nic sie nie dzieje.' },
      { id: 2, title: 'Konkurencja sprzedaje lepszy bimber', description: 'Wplywy wszystkich graczy spadają o 1' },
      { id: 3, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 1.1 na Manhattanie' },
      { id: 4, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 1.2 na Manhattanie' },
      { id: 5, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 1.3 na Manhattanie' },
      { id: 6, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 1.4 na Manhattanie' },
      { id: 7, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 2.1 w Bronxie' },
      { id: 8, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 2.2 w Bronxie' },
      { id: 9, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 2.3 w Bronxie' },
      { id: 10, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 2.4 w Bronxie' },
      { id: 11, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 2.5 w Bronxie' },
      { id: 12, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 3.1 w Queens' },
      { id: 13, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 3.2 w Queens' },
      { id: 14, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 3.3 w Queens' },
      { id: 15, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 3.4 w Queens' },
      { id: 16, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 3.5 w Queens' },
      { id: 17, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 3.6 w Queens' },
      { id: 18, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 4.1 w Brooklyn' },
      { id: 19, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 4.2 w Brooklyn' },
      { id: 20, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 4.3 w Brooklyn' },
      { id: 21, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 4.4 w Brooklyn' },
      { id: 22, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 4.5 w Brooklyn' },
      { id: 23, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 4.6 w Brooklyn' },
      { id: 24, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 5.1 w Staten Island' },
      { id: 25, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 5.2 w Staten Island' },
      { id: 26, title: 'Podejrzenia', description: 'Policjant pojawia sie w lokalu 5.3 w Staten Island' },
      { id: 27, title: 'Uszkodzone drogi do Manhattanu', description: 'Przez 1 ture nie mozna przez nie prowadzic transportow (umiesc zetony uszkodzenia drogi)' },
      { id: 28, title: 'Uszkodzone drogi do Bronxu', description: 'Przez 1 ture nie mozna przez nie prowadzic transportow (umiesc zetony uszkodzenia drogi)' },
      { id: 29, title: 'Uszkodzone drogi do Queens', description: 'Przez 1 ture nie mozna przez nie prowadzic transportow (umiesc zetony uszkodzenia drogi)' },
      { id: 30, title: 'Uszkodzone drogi do Brooklynu', description: 'Przez 1 ture nie mozna przez nie prowadzic transportow (umiesc zetony uszkodzenia drogi)' },
      { id: 31, title: 'Uszkodzone drogi do Staten Island', description: 'Przez 1 ture nie mozna przez nie prowadzic transportow (umiesc zetony uszkodzenia drogi)' },
      { id: 32, title: 'Dodatkowy patrol - mosty', description: 'Postaw pionek dodatkowego patrolu na wszystkich mostach' },
      { id: 33, title: 'Dodatkowy patrol - drogi ladowe', description: 'Postaw pionek dodatkowego patrolu na wszystkich drogach ladowych' },
      { id: 34, title: 'Dodatkowy patrol - Manhattan', description: 'Postaw pionek dodatkowego patrolu na wszystkich drogach do Manhattanu' },
      { id: 35, title: 'Dodatkowy patrol - Bronx', description: 'Postaw pionek dodatkowego patrolu na wszystkich drogach do Bronxu' },
      { id: 36, title: 'Dodatkowy patrol - Queens', description: 'Postaw pionek dodatkowego patrolu na wszystkich drogach do Queens' },
      { id: 37, title: 'Dodatkowy patrol - Brooklyn', description: 'Postaw pionek dodatkowego patrolu na wszystkich drogach do Brooklynu' },
      { id: 38, title: 'Dodatkowy patrol - Staten Island', description: 'Postaw pionek dodatkowego patrolu na wszystkich drogach do Staten Island' },
      { id: 39, title: 'Dodatkowy patrol - Bimbrownia', description: 'Postaw pionek dodatkowego patrolu na wszystkich drogach do bimbrowni' },
      { id: 40, title: 'Dodatkowy patrol - Manhattan', description: 'Postaw 2 pionki dodatkowego patrolu na wszystkich drogach do Manhattanu' },
      { id: 41, title: 'Nalot', description: 'Pionek policji pojawia sie w lokalu na Manhattanie o najwyzszym rozglosie ( rozglos = liczba agentow + liczba ulepszen)' },
      { id: 42, title: 'Nalot', description: 'Pionek policji pojawia sie w lokalu w Bronxie o najwyzszym rozglosie ( rozglos = liczba agentow + liczba ulepszen)' },
      { id: 43, title: 'Nalot', description: 'Pionek policji pojawia sie w lokalu w Queens o najwyzszym rozglosie ( rozglos = liczba agentow + liczba ulepszen)' },
      { id: 44, title: 'Nalot', description: 'Pionek policji pojawia sie w lokalu w Brooklynie o najwyzszym rozglosie ( rozglos = liczba agentow + liczba ulepszen)' },
      { id: 45, title: 'Nalot', description: 'Pionek policji pojawia sie w lokalu w Staten Island o najwyzszym rozglosie ( rozglos = liczba agentow + liczba ulepszen)' },
      { id: 46, title: 'Nalot', description: 'Pionek policji pojawia sie w każdym lokalu na Manhattanie' },
      { id: 47, title: 'Nalot', description: 'Pionek policji pojawia sie w każdym lokalu w Bronxie' },
      { id: 48, title: 'Nalot', description: 'Pionek policji pojawia sie w każdym lokalu w Queens' },
      { id: 49, title: 'Nalot', description: 'Pionek policji pojawia sie w każdym lokalu w Brooklynie' },
      { id: 50, title: 'Nalot', description: 'Pionek policji pojawia sie w każdym lokalu w Staten Island' },
      { id: 51, title: 'Kwarantanna', description: 'Zamknięcie lokalu 1.1 w dzielnicy Manhattan. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 52, title: 'Kwarantanna', description: 'Zamknięcie lokalu 1.2 w dzielnicy Manhattan. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 53, title: 'Kwarantanna', description: 'Zamknięcie lokalu 1.3 w dzielnicy Manhattan. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 54, title: 'Kwarantanna', description: 'Zamknięcie lokalu 1.4 w dzielnicy Manhattan. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 55, title: 'Kwarantanna', description: 'Zamknięcie lokalu 2.1 w dzielnicy Bronx. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 56, title: 'Kwarantanna', description: 'Zamknięcie lokalu 2.2 w dzielnicy Bronx. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 57, title: 'Kwarantanna', description: 'Zamknięcie lokalu 2.3 w dzielnicy Bronx. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 58, title: 'Kwarantanna', description: 'Zamknięcie lokalu 2.4 w dzielnicy Bronx. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 59, title: 'Kwarantanna', description: 'Zamknięcie lokalu 2.5 w dzielnicy Bronx. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 60, title: 'Kwarantanna', description: 'Zamknięcie lokalu 3.1 w dzielnicy Queens. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 61, title: 'Kwarantanna', description: 'Zamknięcie lokalu 3.2 w dzielnicy Queens. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 62, title: 'Kwarantanna', description: 'Zamknięcie lokalu 3.3 w dzielnicy Queens. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 63, title: 'Kwarantanna', description: 'Zamknięcie lokalu 3.4 w dzielnicy Queens. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 64, title: 'Kwarantanna', description: 'Zamknięcie lokalu 3.5 w dzielnicy Queens. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 65, title: 'Kwarantanna', description: 'Zamknięcie lokalu 3.6 w dzielnicy Queens. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 66, title: 'Kwarantanna', description: 'Zamknięcie lokalu 4.1 w dzielnicy Brooklyn. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 67, title: 'Kwarantanna', description: 'Zamknięcie lokalu 4.2 w dzielnicy Brooklyn. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 68, title: 'Kwarantanna', description: 'Zamknięcie lokalu 4.3 w dzielnicy Brooklyn. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 69, title: 'Kwarantanna', description: 'Zamknięcie lokalu 4.4 w dzielnicy Brooklyn. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 70, title: 'Kwarantanna', description: 'Zamknięcie lokalu 4.5 w dzielnicy Brooklyn. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 71, title: 'Kwarantanna', description: 'Zamknięcie lokalu 4.6 w dzielnicy Brooklyn. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 72, title: 'Kwarantanna', description: 'Zamknięcie lokalu 5.1 w dzielnicy Staten Island. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 73, title: 'Kwarantanna', description: 'Zamknięcie lokalu 5.2 w dzielnicy Staten Island. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 74, title: 'Kwarantanna', description: 'Zamknięcie lokalu 5.3 w dzielnicy Staten Island. Agenci z lokalu wracają na rękę graczy, alkohol do bimbrowni. Ulepszenia lokalu pozostają na planszy.' },
      { id: 75, title: 'Upadajace morale', description: 'Kazdy gracz straci po 1 punkcie wplywow, chyba ze gracze zrzuca sie (niejawnie) na lapowke w wys. 200$.' },
      { id: 76, title: 'Dobry bimber', description: 'Alkohol rodziny jest najlepszy na rynku. Wszyscy gracze otrzymuja 1 pkt wplywow.' },
      { id: 77, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 1.1 w dzielnicy Manhattan - cały alkohol wraca do bimbrowni' },
      { id: 78, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 1.2 w dzielnicy Manhattan - cały alkohol wraca do bimbrowni' },
      { id: 79, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 1.3 w dzielnicy Manhattan - cały alkohol wraca do bimbrowni' },
      { id: 80, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 1.4 w dzielnicy Manhattan - cały alkohol wraca do bimbrowni' },
      { id: 81, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 2.1 w dzielnicy Bronx - cały alkohol wraca do bimbrowni' },
      { id: 82, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 2.2 w dzielnicy Bronx - cały alkohol wraca do bimbrowni' },
      { id: 83, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 2.3 w dzielnicy Bronx - cały alkohol wraca do bimbrowni' },
      { id: 84, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 2.4 w dzielnicy Bronx - cały alkohol wraca do bimbrowni' },
      { id: 85, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 2.5 w dzielnicy Bronx - cały alkohol wraca do bimbrowni' },
      { id: 86, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 3.1 w dzielnicy Queens - cały alkohol wraca do bimbrowni' },
      { id: 87, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 3.2 w dzielnicy Queens - cały alkohol wraca do bimbrowni' },
      { id: 88, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 3.3 w dzielnicy Queens - cały alkohol wraca do bimbrowni' },
      { id: 89, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 3.4 w dzielnicy Queens - cały alkohol wraca do bimbrowni' },
      { id: 90, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 3.5 w dzielnicy Queens - cały alkohol wraca do bimbrowni' },
      { id: 91, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 3.6 w dzielnicy Queens - cały alkohol wraca do bimbrowni' },
      { id: 92, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 4.1 w dzielnicy Brooklyn - cały alkohol wraca do bimbrowni' },
      { id: 93, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 4.2 w dzielnicy Brooklyn - cały alkohol wraca do bimbrowni' },
      { id: 94, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 4.3 w dzielnicy Brooklyn - cały alkohol wraca do bimbrowni' },
      { id: 95, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 4.4 w dzielnicy Brooklyn - cały alkohol wraca do bimbrowni' },
      { id: 96, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 4.5 w dzielnicy Brooklyn - cały alkohol wraca do bimbrowni' },
      { id: 97, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 4.6 w dzielnicy Brooklyn - cały alkohol wraca do bimbrowni' },
      { id: 98, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 5.1 w dzielnicy Staten Island - cały alkohol wraca do bimbrowni' },
      { id: 99, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 5.2 w dzielnicy Staten Island - cały alkohol wraca do bimbrowni' },
      { id: 100, title: 'Wykrycie alkoholu', description: 'Wykrycie skladu alkoholu w lokalu 5.3 w dzielnicy Staten Island - cały alkohol wraca do bimbrowni' },
    ];
